###
GET http://localhost:7000/users

###
GET http://localhost:7000/users/6fae2698-5322-4c49-9a0b-a6312198e299
###
POST  http://localhost:7000/users
Content-Type: application/json

{
            "name": "Jhonson",
            "email" : "jhonson@gmail.com",
            "password": "1234561",
            "role": "user", 
            "phone": "0776526",
            "province": "Banten",
            "city": "Tangerang Selatan"
}

###
PATCH   http://localhost:7000/users/6fae2698-5322-4c49-9a0b-a6312198e299
Content-Type: application/json

{
            "name": "Sarah Dawson",
            "email" : "sarah@gmail.com",
            "password": "1234561",
            "role": "user", 
            "phone": "0831545",
            "province": "Jakarta",
            "city": "Jakarta Pusat"
}


###
DELETE  http://localhost:7000/users/69c8747f-279a-4830-8d3b-8b3ddbbd337d

//Login
###
POST  http://localhost:7000/login
Content-Type: application/json

{
    "email": "jhonson@gmail.com",
    "password": "1234561"
}



//Me
###
GET http://localhost:7000/me


//logout
###
DELETE http://localhost:7000/logout

###
GET   http://localhost:7000/items


###
POST   http://localhost:7000/items
Content-Type: application/json

{
    "itemName": "Kue",
    "files": "ajshjgjas.jpg"
}
